# Generated by Django 3.2.7 on 2021-09-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rafvaxx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='doses',
            field=models.CharField(max_length=2),
        ),
    ]
