# Generated by Django 3.2.7 on 2021-09-16 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rafvaxx', '0002_alter_vaccine_doses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='doses',
            field=models.IntegerField(default='', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
